import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

function generateReport(result) {
  const doc = new jsPDF();

  const reportId =
    "VAJRA-" +
    Math.floor(Math.random() * 900000 + 100000);

  const date = new Date().toLocaleString();

  const score = Number(result.fraud_score);

  const risk =
    score >= 70
      ? "HIGH RISK"
      : score >= 40
      ? "MEDIUM RISK"
      : "LOW RISK";

  // -----------------------------
  // HEADER
  // -----------------------------

  doc.setFillColor(18, 33, 61);
  doc.rect(0, 0, 220, 35, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.text("VAJRA AI", 15, 18);

  doc.setFontSize(11);
  doc.text(
    "Cyber Fraud Investigation Report",
    15,
    28
  );

  doc.setTextColor(0, 0, 0);

  // -----------------------------
  // REPORT INFO
  // -----------------------------

  doc.setFontSize(15);
  doc.text("Report Information", 15, 48);

  autoTable(doc, {
    startY: 53,

    head: [["Field", "Value"]],

    body: [
      ["Report ID", reportId],
      ["Generated", date],
      ["Fraud Score", `${result.fraud_score}%`],
      ["Risk Level", risk],
      ["AI Confidence", `${result.confidence}%`],
      ["Decision", result.decision],
    ],

    theme: "grid",

    headStyles: {
      fillColor: [18, 33, 61],
    },
  });

  // -----------------------------
  // MODEL OUTPUT
  // -----------------------------

  doc.text(
    "AI Model Analysis",
    15,
    doc.lastAutoTable.finalY + 15
  );

  autoTable(doc, {
    startY: doc.lastAutoTable.finalY + 20,

    head: [["Model", "Prediction"]],

    body: [
      [
        "Random Forest",
        `${result.random_forest_score}%`,
      ],

      [
        "Neural Network",
        result.neural_network_score,
      ],

      [
        "Final Decision",
        result.decision,
      ],
    ],

    theme: "striped",

    headStyles: {
      fillColor: [41, 64, 95],
    },
  });

  // -----------------------------
  // AI EXPLANATION
  // -----------------------------

  doc.text(
    "AI Risk Explanation",
    15,
    doc.lastAutoTable.finalY + 15
  );

  let y = doc.lastAutoTable.finalY + 25;

  if (result.reasons) {
    result.reasons.forEach((reason) => {
      doc.text("• " + reason, 20, y);
      y += 8;
    });
  }

  // -----------------------------
  // ACTION
  // -----------------------------

  y += 8;

  doc.setFontSize(15);
  doc.text(
    "Recommended Action",
    15,
    y
  );

  y += 10;

  doc.setFontSize(11);

  doc.text(
    result.recommended_action,
    15,
    y,
    {
      maxWidth: 175,
    }
  );

  // -----------------------------
  // SUMMARY
  // -----------------------------

  y += 30;

  doc.setFontSize(15);

  doc.text(
    "AI Summary",
    15,
    y
  );

  y += 10;

  doc.setFontSize(11);

  doc.text(
    result.ai_summary,
    15,
    y,
    {
      maxWidth: 180,
    }
  );

  // -----------------------------
  // FOOTER
  // -----------------------------

  doc.setDrawColor(180);

  doc.line(
    15,
    282,
    195,
    282
  );

  doc.setFontSize(10);

  doc.setTextColor(90);

  doc.text(
    "Generated by VAJRA AI | On its way to secure every digital transaction.",
    15,
    288
  );

  doc.save(
    `VAJRA_Cyber_Report_${reportId}.pdf`
  );
}

export default generateReport;